### ISSUE TITLE
Format detection less particular in comparison with PyCo

### ISSUE THREAD

**Issue by mcrot** [ComputationalMechanics/SurfaceTopography#14]
In TopoBank, a special error message is displayed, when the format of the uploaded file is not recognized.
For example, when you upload a Javascript source code file as a data file, you'll get an error message:
![grafik](https://user-images.githubusercontent.com/9113541/86011333-d85c4e00-ba1c-11ea-8a42-254c67f96e0d.png)
This happens, because PyCo throws a `CannotDetectFileFormat`exception:
```python
fn = "/home/michael/prj/imtek/topobank/topobank/static/js/project.js"
import PyCo
PyCo.Topography.IO.detect_format(fn)
Traceback (most recent call last):
  File "/home/michael/miniconda3/envs/topobank/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-42-04de270c6ed5>", line 1, in <module>
    PyCo.Topography.IO.detect_format(fn)
  File "/home/michael/miniconda3/envs/topobank/lib/python3.7/site-packages/PyCo/Topography/IO/__init__.py", line 89, in detect_format
    raise CannotDetectFileFormat(msg)
```
With `SurfaceTopography` in the current version, the format detection returns "asc":
```python
import SurfaceTopography
SurfaceTopography.__version__ # 0.90.0
SurfaceTopography.IO.detect_format(fn)   # returns 'asc'
```
In TopoBank instead another error message is displayed, because of some later step:
![grafik](https://user-images.githubusercontent.com/9113541/86011905-92ec5080-ba1d-11ea-8b0c-08b1fd89302c.png)

This results from another exception and is much less useful for the user.

Would it be possible, that the reader raises `CannotDetectFileFormat` again?

**Comment by mcrot** [comment]
Seems to be fixed by patch for #16, adding a test case for this.
